### ISSUE TITLE
No database found to handle jdbc:mongodb://localhost:27017

### ISSUE THREAD

**Issue by matteus6007** [flyway/flyway-docker#141]
I am using the latest version `flyway/flyway:10.11.0`, but when I try to run migration scripts for mongodb (running locally using Docker) I get the following error:

```
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mongodb://localhost:27017
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:55)        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:89)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.getDataSource(ClassicConfiguration.java:118)       
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1696)
        at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:896)
        at org.flywaydb.commandline.configuration.LegacyConfigurationManager.getConfiguration(LegacyConfigurationManager.java:79)
        at org.flywaydb.commandline.configuration.ConfigurationManagerImpl.getConfiguration(ConfigurationManagerImpl.java:39)
        at org.flywaydb.commandline.Main.main(Main.java:103)
```

I have tried changing the URL to the name of the docker container and also attaching to the same container network.

Using the CLI of the same version the migration runs without any issues.

**Comment by piers-williams** [comment]
Thank you for raising this issue.

We have consolidated the docker code into [flyway/flyway](https://github.com/flyway/flyway)

If this is still an issue that you would like us to look into, please re-raise it there
