### ISSUE TITLE
redgate/flyway:10.21.0-alpine image fails for MongoDB with a NoSuchMethodError

### ISSUE THREAD

**Issue by jagregory** [flyway/flyway-docker#164]
I'm just running the vanilla image with no customisations. The `redgate/flyway:10.21.0-alpine` image results in the error below. 10.20.0 worked fine and downgrading resolves the issue.

```
Flyway Community Edition 10.21.0 by Redgate
See release notes here: https://rd.gt/416ObMi
Flyway Pipelines are not active for this project. Learn more here: https://flyway.red-gate.com
Exception in thread "main" java.lang.NoSuchMethodError: 'com.mongodb.spi.dns.InetAddressResolver com.mongodb.internal.connection.ServerAddressHelper.getInetAddressResolver(com.mongodb.MongoClientSettings)'
	at com.mongodb.client.internal.MongoClientImpl.getStreamFactory(MongoClientImpl.java:233)
	at com.mongodb.client.internal.MongoClientImpl.createCluster(MongoClientImpl.java:224)
	at com.mongodb.client.internal.MongoClientImpl.<init>(MongoClientImpl.java:74)
	at com.mongodb.client.MongoClients.create(MongoClients.java:108)
	at com.mongodb.client.MongoClients.create(MongoClients.java:50)
	at com.dbschema.mongo.MongoClientWrapper.<init>(MongoClientWrapper.java:102)
	at com.dbschema.mongo.MongoService.<init>(MongoService.java:32)
	at com.dbschema.mongo.MongoConnection.<init>(MongoConnection.java:27)
	at com.dbschema.MongoJdbcDriver.connect(MongoJdbcDriver.java:94)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:1043)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:1008)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:827)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:844)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:905)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:945)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:1066)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:972)
	at org.flywaydb.commandline.Main.main(Main.java:895)
```

**Comment by piers-williams** [comment]
Closing this as believe that it has now been fixed
